### ISSUE TITLE
Getting error when starting Webpack

### ISSUE THREAD

**Issue by pankaj-arunsingh** [sayar/ReactMVA#1]
Hi Sayar,
I followed the procedure of installing webpack and npm modules for this project but I am getting below error when giving command npm run start-webpack-server.
![image](https://cloud.githubusercontent.com/assets/8179097/22638724/2496c41c-ec9e-11e6-9237-31a16f53faff.png)
Please help.

**Comment by sayar** [comment]
Hello, the repo and the videos are fairly out of date. We're working on a new version to be released soon.

**Comment by sayar** [comment]
@pankaj-arunsingh I updated the webpack scripts throughout. You should no longer experience that error.

**Comment by pankaj-arunsingh** [comment]
Thanks a lot @sayar . This really helped.
